Repository DeveloperAcademy-POSTECH/MC2_2thCo.6thPlatoon, pull requests merged in 2023-05, with the labels that each got.

#14 Feat/#10 implement interviewdetails modal view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Resources/Constants.swift
  Pressor/Pressor/Resources/Extensions/Color+.swift
  Pressor/Pressor/Resources/Extensions/View+DismissKeyboard.swift
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
Labels: ✨ Feat

#19 Feat/#7 implement interview UI
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Views/InterviewViews/InterviewListView.swift
Labels: ✨ Feat

#20 Feat/#8 implement interview recording view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Resources/Constants.swift
  Pressor/Pressor/Resources/Extensions/Color+.swift
  Pressor/Pressor/Resources/Extensions/View+DismissKeyboard.swift
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/AudioVisualizerView.swift
Labels: ✨ Feat

#18 Feat/#2 implement recordview stt
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Info.plist
  Pressor/Pressor/Models/Interview.swift
  Pressor/Pressor/Models/InterviewDetail.swift
  Pressor/Pressor/Models/Record.swift
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/Resources/Extensions/Date+.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/TestViews/InterviewDetailTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingTestView.swift
  Pressor/Pressor/Views/TestViews/MainTestView.swift
Labels: ✨ Feat

#17 [Feat/#4] MainRecordView의 탭바, 내비게이션 바 및 InterviewRecordingView 연결 버튼 구현
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: ✨ Feat

#21 Feat/#3 implement audio visualizer through mic
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/ViewModels/AudioInputVIewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/AudioVisualizerView.swift
Labels: ✨ Feat

#27 Feat/#24 implement add script modal view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Views/RecordViews/AddScriptModalView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: ✨ Feat

#23 [Feat/#22] InterviewRecordingView, EndTestView, MainRecordingView 개선
  Pressor/Pressor.xcodeproj/xcshareddata/xcschemes/Pressor.xcscheme
  Pressor/Pressor/Assets.xcassets/mic_button.imageset/Contents.json
  Pressor/Pressor/Assets.xcassets/mic_button.imageset/mic_button.png
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
Labels: ✨ Feat

#35 Origin/feat/#25 implement interview instance managing
  Pressor/Pressor.xcodeproj/xcshareddata/xcschemes/Pressor.xcscheme
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/TestViews/InterviewDetailTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingTestView.swift
  Pressor/Pressor/Views/TestViews/MainTestView.swift
Labels: ✨ Feat, 🛠️ Fix

#36 [Feat/#31] implement color extension 색상 추가
  Pressor/Pressor/Resources/Extensions/Color+.swift
Labels: ✨ Feat

#39 [Feat/#37] InterviewRecordingView에 취소 버튼 구현
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: ✨ Feat

#41 Feat/#32 implement main record view animation
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: ✨ Feat

#44 Feat/#42 merge test views
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
  Pressor/Pressor/Views/TestViews/InterviewDetailTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
Labels: ✨ Feat, 🛠️ Fix

#38 Feat/#28 implement interview script modeling script crud
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Models/InterviewScriptModel.swift
  Pressor/Pressor/ViewModels/InterviewViewModel.swift
  Pressor/Pressor/Views/TestViews/EditInterviewScriptTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewScriptTestView.swift
Labels: ✨ Feat

#49 Feat/#47 fix interviewrecordingview animation
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
Labels: ✨ Feat

#52 Feat/#51 implement permission manager
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/ViewModels/PermissionManager.swift
Labels: ✨ Feat

#54 Feat/#48 responding script view ux changes
  Pressor/Pressor/Models/InterviewScriptModel.swift
  Pressor/Pressor/ViewModels/InterviewViewModel.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/AddScriptModalView.swift
  Pressor/Pressor/Views/RecordViews/AudioVisualizerView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
  Pressor/Pressor/Views/TestViews/EditInterviewScriptTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewDetailTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingTestView.swift
  Pressor/Pressor/Views/TestViews/InterviewScriptTestView.swift
  Pressor/Pressor/Views/TestViews/MainTestView.swift
Labels: 🛠️ Fix

#61 Fix/#60 main record view navigation bar item disable
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingScriptView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: 🐛 bug, 🛠️ Fix

#62 Feat/#56 separate script add view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/ViewModels/InterviewViewModel.swift
  Pressor/Pressor/Views/RecordViews/AddScriptView.swift
  Pressor/Pressor/Views/RecordViews/CheckScriptView.swift
  Pressor/Pressor/Views/RecordViews/EditScriptView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: ✨ Feat

#67 Feat/#65 implement setting view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Assets.xcassets/app_icon.imageset/Contents.json
  Pressor/Pressor/Assets.xcassets/app_icon.imageset/Group.png
  Pressor/Pressor/Views/RecordViews/AddScriptView.swift
  Pressor/Pressor/Views/RecordViews/CheckScriptView.swift
  Pressor/Pressor/Views/RecordViews/EditScriptView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
  Pressor/Pressor/Views/RecordViews/SettingView.swift
Labels: ✨ Feat

#63 Feat/#33 interviewbubble record play stop display
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor.xcodeproj/xcshareddata/xcschemes/Pressor.xcscheme
  Pressor/Pressor/Info.plist
  Pressor/Pressor/Models/Interview.swift
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/Resources/Extensions/Array+SafeIndex.swift
  Pressor/Pressor/Resources/Extensions/BlurBackground.swift
  Pressor/Pressor/Resources/Extensions/Color+.swift
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/ViewModels/InterviewBubbleManager.swift
  Pressor/Pressor/Views/InterviewViews/InterviewDetailView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingScriptView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
  Pressor/Pressor/Views/TestViews/InterviewRecordingEndTestView.swift
Labels: ✨ Feat

#72 Fix/#70 fix interview bubble UI/interview edit bugfix
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/ViewModels/InterviewBubbleManager.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewDetailView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingScriptView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: 🐛 bug, 🛠️ Fix

#75 Feat/#71 implement interview list view
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Models/Interview.swift
  Pressor/Pressor/Models/Record.swift
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/Resources/Constants.swift
  Pressor/Pressor/Resources/Extensions/Array+AppStorage.swift
  Pressor/Pressor/Resources/Extensions/Color+.swift
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/ViewModels/InterviewBubbleManager.swift
  Pressor/Pressor/ViewModels/InterviewListViewModel.swift
  Pressor/Pressor/ViewModels/RoutingManager.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewDetailView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewListView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingScriptView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: 🐛 bug, ✨ Feat, 🛠️ Fix

#78 Feat #76 fix managing speechrecognizer
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
Labels: ✨ Feat, 🛠️ Fix

#79 Fix/#77 fix interview init timing
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Models/Interview.swift
  Pressor/Pressor/PressorApp.swift
  Pressor/Pressor/ViewModels/InterviewListViewModel.swift
  Pressor/Pressor/ViewModels/VoiceViewModel.swift
  Pressor/Pressor/Views/InterviewViews/InterviewDetailView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewListView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailChatEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewModals/InterviewDetailEditModalView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingScriptView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewRecordingView.swift
  Pressor/Pressor/Views/RecordViews/MainRecordView.swift
Labels: 🛠️ Fix

#83 Feat/#80 update interviewbubble UI
  Pressor/Pressor.xcodeproj/project.pbxproj
  Pressor/Pressor/Assets.xcassets/EmptyInterview.imageset/Contents.json
  Pressor/Pressor/Assets.xcassets/EmptyInterview.imageset/EmptyInterview.png
  Pressor/Pressor/Assets.xcassets/EmptyInterview.imageset/EmptyInterview@2x.png
  Pressor/Pressor/Assets.xcassets/EmptyInterview.imageset/EmptyInterview@3x.png
  Pressor/Pressor/Resources/RecordBubble.swift
  Pressor/Pressor/Resources/ToggleStyle.swift
  Pressor/Pressor/ViewModels/InterviewBubbleManager.swift
  Pressor/Pressor/Views/InterviewViews/InterviewDetailView.swift
  Pressor/Pressor/Views/InterviewViews/InterviewListView.swift
Labels: ✨ Feat
